package client.Interface;

import client.AuthClient;
import utils.BackgroundTaskWithLoading;
import client.Components.CartCard2;
import client.Components.PaymentDialog;
import enums.OrderStatus;
import java.awt.Color;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicTabbedPaneUI;
import model.AuthToken;
import model.Customer;
import model.Order;
import model.OrderItem;
import model.Products;
import model.User;
import utils.TokenStorage;

public class HomePage extends javax.swing.JFrame {

//    private int quantity = 1;
//    private JLabel quantityLabel;
//    private Cursor originalCursor;
    private final AuthToken token;
    private User user;

    /**
     * Creates new form HomePage
     *
     * @param token
     */
    public HomePage(AuthToken token) {
        initComponents();
        this.token = token;
//        System.out.println(token);
        // Load user data in background
        new BackgroundTaskWithLoading<>(
                this,
                "Loading your dashboard...",
                () -> new AuthClient().requestUserByToken(token),
                user -> {
                    if (user != null) {
//                        System.out.println(user.toString());
                        this.user = user;
                        postInitComponents(); // Now called after user is set
                        this.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "Failed to load user data.", "Error", JOptionPane.ERROR_MESSAGE);
                        this.dispose(); // Close the window if data is missing
                    }
                }
        ).execute();
    }

    private void postInitComponents() {
        // Re-inject the now-initialized foodItemSection1 into menuPanel2
        menuPanel2.setFoodItemSection(foodItemSection1, token);
//        menuPanel2.setToken(token);
        userNameDisplay.setText(this.user.getFullName());
//        System.out.println(this.user.getFullName());
        orderHistorySection1 = new client.Components.OrderHistorySection(this.user, this.token);
        mainTab.addTab("tab2", orderHistorySection1);
        userProfileSection1 = new client.Components.UserProfileSection((Customer) this.user, this.token);
        
        mainTab.addTab("tab3", userProfileSection1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(1000, 20), new java.awt.Dimension(32767, 32767));
        userNameDisplay = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(1000, 20), new java.awt.Dimension(32767, 32767));
        profileIcon = new javax.swing.JLabel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(1000, 20), new java.awt.Dimension(32767, 32767));
        jPanel11 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(100, 20), new java.awt.Dimension(32767, 32767));
        totalPriceCart = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(50, 20), new java.awt.Dimension(32767, 32767));
        totalPriceCart1 = new javax.swing.JLabel();
        button1 = new client.Components.Button();
        cartPanel = new client.Components.CartPanel();
        jPanel3 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(1000, 30), new java.awt.Dimension(32767, 32767));
        jLabel1 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(1000, 30), new java.awt.Dimension(32767, 32767));
        jSeparator1 = new javax.swing.JSeparator();
        homePage = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        myHistory = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        logoutPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(2000, 10), new java.awt.Dimension(32767, 32767));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(2000, 10), new java.awt.Dimension(32767, 32767));
        mainTab = new javax.swing.JTabbedPane();
        menuPanel2 = new client.Components.MenuPanel();
        foodItemSection1 = new client.Components.FoodItemSection();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 600));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(1000, 70));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));
        jPanel6.add(filler4);

        userNameDisplay.setText("Name");
        userNameDisplay.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel6.add(userNameDisplay);
        jPanel6.add(filler9);

        profileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user.png"))); // NOI18N
        profileIcon.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        profileIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileIconMouseExited(evt);
            }
        });
        jPanel6.add(profileIcon);
        jPanel6.add(filler10);

        jPanel2.add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanel11.setOpaque(false);
        jPanel11.setPreferredSize(new java.awt.Dimension(400, 110));

        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(200, 20));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0);
        flowLayout2.setAlignOnBaseline(true);
        jPanel7.setLayout(flowLayout2);

        jLabel9.setText("Total");
        jPanel7.add(jLabel9);
        jPanel7.add(filler7);

        totalPriceCart.setText("RM 0");
        jPanel7.add(totalPriceCart);

        jPanel11.add(jPanel7);

        jPanel13.setOpaque(false);
        jPanel13.setPreferredSize(new java.awt.Dimension(200, 20));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0);
        flowLayout1.setAlignOnBaseline(true);
        jPanel13.setLayout(flowLayout1);

        jLabel10.setText("Delivery Fees");
        jPanel13.add(jLabel10);
        jPanel13.add(filler8);

        totalPriceCart1.setText("RM 5");
        jPanel13.add(totalPriceCart1);

        jPanel11.add(jPanel13);

        button1.setText("Check out");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel11.add(button1);

        jPanel2.add(jPanel11, java.awt.BorderLayout.SOUTH);
        jPanel2.add(cartPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(120, 600));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.add(filler1);

        jLabel1.setText("Food Order System");
        jPanel3.add(jLabel1);
        jPanel3.add(filler2);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 255));
        jSeparator1.setPreferredSize(new java.awt.Dimension(1000, 5));
        jPanel3.add(jSeparator1);

        homePage.setBackground(new java.awt.Color(255, 255, 255));
        homePage.setPreferredSize(new java.awt.Dimension(1000, 30));
        homePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homePageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homePageMouseExited(evt);
            }
        });
        homePage.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 7, 5));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/homeIcon.png"))); // NOI18N
        homePage.add(jLabel4);

        jLabel5.setText("Home");
        homePage.add(jLabel5);

        jPanel3.add(homePage);

        myHistory.setBackground(new java.awt.Color(255, 255, 255));
        myHistory.setPreferredSize(new java.awt.Dimension(1000, 30));
        myHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myHistoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myHistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                myHistoryMouseExited(evt);
            }
        });
        myHistory.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 7, 5));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cartIcon.png"))); // NOI18N
        myHistory.add(jLabel7);

        jLabel8.setText("History");
        myHistory.add(jLabel8);

        jPanel3.add(myHistory);

        logoutPanel.setBackground(new java.awt.Color(255, 255, 255));
        logoutPanel.setPreferredSize(new java.awt.Dimension(1000, 30));
        logoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutPanelMouseExited(evt);
            }
        });
        logoutPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 7, 5));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logout.png"))); // NOI18N
        logoutPanel.add(jLabel2);

        jLabel3.setText("Logout");
        logoutPanel.add(jLabel3);

        jPanel3.add(logoutPanel);

        getContentPane().add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(1000, 70));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 50, 5));
        jPanel5.add(filler5);
        jPanel5.add(filler6);

        jPanel1.add(jPanel5, java.awt.BorderLayout.NORTH);

        mainTab.setOpaque(true);
        mainTab.setPreferredSize(new java.awt.Dimension(200, 200));
        mainTab.setUI(new BasicTabbedPaneUI() {
            @Override
            protected int calculateTabAreaHeight(int tabPlacement, int horizRunCount, int maxTabHeight) {
                return 0;
            }
        });
        mainTab.addTab("tab1", menuPanel2);

        foodItemSection1.setBackground(new java.awt.Color(255, 255, 255));
        mainTab.addTab("tab2", foodItemSection1);

        jPanel1.add(mainTab, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseClicked

        String res = new AuthClient().handleAuthLogout(this.token);
        if (res != null) {
            JOptionPane.showMessageDialog(this,
                    res,
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        this.setVisible(false);
        new LoginPage().setVisible(true);
        this.dispose();
        if (!TokenStorage.deleteToken()) {
            System.out.println("Warning: Failed to remove saved session. ser file not removed");
        }
    }//GEN-LAST:event_logoutPanelMouseClicked

    private void homePageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePageMouseClicked
        mainTab.setSelectedIndex(0);
        menuPanel2.refreshProductData();
    }//GEN-LAST:event_homePageMouseClicked

    private void homePageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePageMouseEntered
        homePage.setBackground(new Color(160, 160, 160));
//        originalCursor = jPanel9.getCursor(); // Save current cursor
        homePage.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_homePageMouseEntered

    private void homePageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePageMouseExited
        homePage.setBackground(Color.white);
        homePage.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_homePageMouseExited

    private void logoutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseEntered
        logoutPanel.setBackground(new Color(160, 160, 160));
//        originalCursor = jPanel8.getCursor(); // Save current cursor
        logoutPanel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutPanelMouseEntered

    private void logoutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseExited
        logoutPanel.setBackground(Color.white);
        logoutPanel.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_logoutPanelMouseExited

    private void myHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myHistoryMouseClicked
        mainTab.setSelectedIndex(2);
       orderHistorySection1.refreshHistoryData();
    }//GEN-LAST:event_myHistoryMouseClicked

    private void myHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myHistoryMouseEntered
        myHistory.setBackground(new Color(160, 160, 160));
//        originalCursor = jPanel10.getCursor(); // Save current cursor
        myHistory.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_myHistoryMouseEntered

    private void myHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myHistoryMouseExited
        myHistory.setBackground(Color.white);
        myHistory.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_myHistoryMouseExited

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        var cards = cartPanel.getItemMap();
        if (cards.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Your Card is Empty", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        List<OrderItem> items = new ArrayList<>();
        double totalPrice = 0;
        for (var card : cards.entrySet()) {
            CartCard2 cartcard = card.getValue();
            Products item = cartcard.getItem();
            OrderItem newOrderItem = new OrderItem(item, cartcard.getQuantity());
            double cardPrice = item.getPrice() * cartcard.getQuantity();
            totalPrice = totalPrice + cardPrice;
            items.add(newOrderItem);
        }
        // get current logined user, now don have user

        Order newOrder = new Order((Customer) user, OrderStatus.PENDING, totalPrice, items);

        PaymentDialog dialog = new PaymentDialog(this, newOrder, token, cartPanel);
        dialog.setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed

    private void profileIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileIconMouseEntered
        profileIcon.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_profileIconMouseEntered

    private void profileIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileIconMouseClicked
        mainTab.setSelectedIndex(3);
    }//GEN-LAST:event_profileIconMouseClicked

    private void profileIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileIconMouseExited
        profileIcon.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_profileIconMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private client.Components.Button button1;
    public static client.Components.CartPanel cartPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private client.Components.FoodItemSection foodItemSection1;
    private javax.swing.JPanel homePage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel logoutPanel;
    public static javax.swing.JTabbedPane mainTab;
    private client.Components.MenuPanel menuPanel2;
    private javax.swing.JPanel myHistory;
    private javax.swing.JLabel profileIcon;
    public static javax.swing.JLabel totalPriceCart;
    public static javax.swing.JLabel totalPriceCart1;
    private javax.swing.JLabel userNameDisplay;
    // End of variables declaration//GEN-END:variables
    private client.Components.OrderHistorySection orderHistorySection1;
    private client.Components.UserProfileSection userProfileSection1;

}
