/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client;

import java.io.IOException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicTabbedPaneUI;

/**
 *
 * @author ejunk
 */
public class HomePage extends javax.swing.JFrame {

    private int quantity = 1;
    private JLabel quantityLabel;

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(1000, 20), new java.awt.Dimension(32767, 32767));
        jLabel6 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(1000, 20), new java.awt.Dimension(32767, 32767));
        jPanel11 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(100, 20), new java.awt.Dimension(32767, 32767));
        jLabel10 = new javax.swing.JLabel();
        button1 = new client.Components.Button();
        cartPanel = new client.Components.CartPanel();
        jPanel3 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(1000, 30), new java.awt.Dimension(32767, 32767));
        jLabel1 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(1000, 30), new java.awt.Dimension(32767, 32767));
        jSeparator1 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(2000, 10), new java.awt.Dimension(32767, 32767));
        textField1 = new client.Components.TextField();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(2000, 10), new java.awt.Dimension(32767, 32767));
        mainTab = new javax.swing.JTabbedPane();
        menuPanel1 = new client.Components.MenuPanel();
        jPanel4 = new javax.swing.JPanel();
        foodItemSection1 = new client.Components.FoodItemSection();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 400));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel6.setPreferredSize(new java.awt.Dimension(1000, 70));
        jPanel6.add(filler4);

        jLabel6.setText("My Orders");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel6.add(jLabel6);
        jPanel6.add(filler3);

        jPanel2.add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanel11.setPreferredSize(new java.awt.Dimension(1000, 70));

        jPanel7.setPreferredSize(new java.awt.Dimension(200, 20));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0);
        flowLayout2.setAlignOnBaseline(true);
        jPanel7.setLayout(flowLayout2);

        jLabel9.setText("Total");
        jPanel7.add(jLabel9);
        jPanel7.add(filler7);

        jLabel10.setText("RM 100");
        jPanel7.add(jLabel10);

        jPanel11.add(jPanel7);

        button1.setText("Check out");
        jPanel11.add(button1);

        jPanel2.add(jPanel11, java.awt.BorderLayout.SOUTH);
        jPanel2.add(cartPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(120, 400));
        jPanel3.add(filler1);

        jLabel1.setText("SYStem Name");
        jPanel3.add(jLabel1);
        jPanel3.add(filler2);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 255));
        jSeparator1.setPreferredSize(new java.awt.Dimension(1000, 5));
        jPanel3.add(jSeparator1);

        jPanel9.setPreferredSize(new java.awt.Dimension(1000, 30));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 7, 5));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/homeIcon.png"))); // NOI18N
        jPanel9.add(jLabel4);

        jLabel5.setText("Home");
        jPanel9.add(jLabel5);

        jPanel3.add(jPanel9);

        jPanel10.setPreferredSize(new java.awt.Dimension(1000, 30));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 7, 5));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cartIcon.png"))); // NOI18N
        jPanel10.add(jLabel7);

        jLabel8.setText("Order");
        jPanel10.add(jLabel8);

        jPanel3.add(jPanel10);

        jPanel8.setPreferredSize(new java.awt.Dimension(1000, 30));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 7, 5));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logout.png"))); // NOI18N
        jPanel8.add(jLabel2);

        jLabel3.setText("Logout");
        jPanel8.add(jLabel3);

        jPanel3.add(jPanel8);

        getContentPane().add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(1000, 70));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 50, 5));
        jPanel5.add(filler5);

        textField1.setText("textField1");
        textField1.setPreferredSize(new java.awt.Dimension(400, 29));
        jPanel5.add(textField1);
        jPanel5.add(filler6);

        jPanel1.add(jPanel5, java.awt.BorderLayout.NORTH);

        mainTab.setPreferredSize(new java.awt.Dimension(200, 200));
        mainTab.setUI(new BasicTabbedPaneUI() {
            @Override
            protected int calculateTabAreaHeight(int tabPlacement, int horizRunCount, int maxTabHeight) {
                return 0;
            }
        });
        mainTab.addTab("tab1", menuPanel1);

        jPanel4.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(foodItemSection1, javax.swing.GroupLayout.DEFAULT_SIZE, 1456, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(foodItemSection1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );

        mainTab.addTab("tab2", jPanel4);

        jPanel1.add(mainTab, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        this.setVisible(false);
        new LoginPage().setVisible(true);
        this.dispose();
        try {
            AuthClient.removeToken();
        } catch (IOException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(this,
                    "Error logout",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        mainTab.setSelectedIndex(0);
    }//GEN-LAST:event_jPanel9MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private client.Components.Button button1;
    public static client.Components.CartPanel cartPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private client.Components.FoodItemSection foodItemSection1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTabbedPane mainTab;
    private client.Components.MenuPanel menuPanel1;
    private client.Components.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
