/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client;

import javax.swing.JOptionPane;
import model.RegisterCredential;

public class RegisterPage extends javax.swing.JFrame {

    public RegisterPage() {
        initComponents();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradientPanel1 = new client.Components.GradientPanel();
        roundPanel1 = new client.Components.RoundPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(32767, 32767));
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        LoginPageTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        usernameField = new client.Components.TextField();
        jLabel3 = new javax.swing.JLabel();
        firstNameField = new client.Components.TextField();
        jLabel4 = new javax.swing.JLabel();
        lastNameField = new client.Components.TextField();
        jLabel5 = new javax.swing.JLabel();
        emailField = new client.Components.TextField();
        jLabel6 = new javax.swing.JLabel();
        contactNumberField = new client.Components.TextField();
        jLabel7 = new javax.swing.JLabel();
        addressField = new client.Components.TextField();
        jLabel2 = new javax.swing.JLabel();
        passwordField = new client.Components.PasswordField();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(1000, 30), new java.awt.Dimension(32767, 32767));
        loginBtn = new client.Components.Button();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(32767, 32767));
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 32767));
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 32767));
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(300, 400), new java.awt.Dimension(32767, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(300, 400), new java.awt.Dimension(32767, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(1000, 30), new java.awt.Dimension(32767, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(1000, 30), new java.awt.Dimension(32767, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        gradientPanel1.setColor2(new java.awt.Color(255, 133, 89));
        gradientPanel1.setLayout(new java.awt.BorderLayout());

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel1.setPreferredSize(new java.awt.Dimension(100, 100));
        roundPanel1.setRoundBottomLeft(30);
        roundPanel1.setRoundBottomRight(30);
        roundPanel1.setRoundTopLeft(30);
        roundPanel1.setRoundTopRight(30);
        roundPanel1.setLayout(new java.awt.BorderLayout());
        roundPanel1.add(filler5, java.awt.BorderLayout.EAST);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(17, 1, 0, 1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        LoginPageTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LoginPageTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginPageTitle.setText("Register");
        jPanel4.add(LoginPageTitle);

        jPanel1.add(jPanel4);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Username");
        jPanel1.add(jLabel1);

        usernameField.setPlaceholder("Enter your username");
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(usernameField);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("First Name");
        jPanel1.add(jLabel3);

        usernameField.setPlaceholder("Enter your username");
        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(firstNameField);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Last Name");
        jPanel1.add(jLabel4);

        usernameField.setPlaceholder("Enter your username");
        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(lastNameField);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Email");
        jPanel1.add(jLabel5);

        usernameField.setPlaceholder("Enter your username");
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        jPanel1.add(emailField);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Contact Number");
        jPanel1.add(jLabel6);

        usernameField.setPlaceholder("Enter your username");
        contactNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberFieldActionPerformed(evt);
            }
        });
        jPanel1.add(contactNumberField);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Address");
        jPanel1.add(jLabel7);

        usernameField.setPlaceholder("Enter your username");
        addressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldActionPerformed(evt);
            }
        });
        jPanel1.add(addressField);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jPanel1.add(passwordField);
        jPanel1.add(filler9);

        loginBtn.setText("Register");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(loginBtn);

        roundPanel1.add(jPanel1, java.awt.BorderLayout.CENTER);
        roundPanel1.add(filler6, java.awt.BorderLayout.WEST);
        roundPanel1.add(filler7, java.awt.BorderLayout.SOUTH);
        roundPanel1.add(filler10, java.awt.BorderLayout.NORTH);

        gradientPanel1.add(roundPanel1, java.awt.BorderLayout.CENTER);
        gradientPanel1.add(filler1, java.awt.BorderLayout.EAST);
        gradientPanel1.add(filler2, java.awt.BorderLayout.WEST);
        gradientPanel1.add(filler3, java.awt.BorderLayout.NORTH);
        gradientPanel1.add(filler4, java.awt.BorderLayout.SOUTH);

        getContentPane().add(gradientPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed

    }//GEN-LAST:event_usernameFieldActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String username = usernameField.getTextValue().strip();
        String password = passwordField.getTextValue().strip();
        String firstName = firstNameField.getTextValue().strip();
        String lastName = lastNameField.getTextValue().strip();
        String contact = contactNumberField.getTextValue().strip();
        String address = addressField.getTextValue().strip();
        String email = emailField.getTextValue().strip();

        if (username.isEmpty() || username.isBlank()) {
            return;
        }

        if (password.isEmpty() || password.isBlank()) {
            return;
        }

        if (firstName.isEmpty() || firstName.isBlank()) {
            return;
        }

        if (lastName.isEmpty() || lastName.isBlank()) {
            return;
        }

        if (contact.isEmpty() || contact.isBlank()) {
            return;
        }

        if (address.isEmpty() || address.isBlank()) {
            return;
        }

        if (email.isEmpty() || email.isBlank()) {
            return;
        }

        RegisterCredential registerCredential = new RegisterCredential(username, password, firstName, lastName, address, contact, email);
        AuthClient auth = new AuthClient();
        auth.setRegisterCredential(registerCredential);
        String response = auth.handleAuthRegister();

        if (response == null) {
            // login success
            this.setVisible(false);
            new HomePage().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    response,
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_loginBtnActionPerformed

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void contactNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberFieldActionPerformed

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginPageTitle;
    private client.Components.TextField addressField;
    private client.Components.TextField contactNumberField;
    private client.Components.TextField emailField;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler9;
    private client.Components.TextField firstNameField;
    private client.Components.GradientPanel gradientPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private client.Components.TextField lastNameField;
    private client.Components.Button loginBtn;
    private client.Components.PasswordField passwordField;
    private client.Components.RoundPanel roundPanel1;
    private client.Components.TextField usernameField;
    // End of variables declaration//GEN-END:variables
}
